project:
  type: "website"
  output-dir: _output
  render:
    - "index.qmd"
    - "update.qmd"
    - "id_key.qmd"
    - "questionnaire.qmd"
    - "handout.qmd"


    

format:
  html: 
    theme:
      light: flatly
    css: styles.css
    grid:
      sidebar-width: 240px
      body-width: 1100px
      margin-width: 200px
      gutter-width: 1.5rem

website:
  title: "Amynthas Project"

  sidebar:
    contents:
      - text: Project Summary
        href: index.qmd
      - text: Project Update
        href: update.qmd
      - text: Identification Key
        href: id_key.qmd
      - text: Questionnaire
        href: questionnaire.qmd
      - text: Handouts
        href: handout.qmd

  navbar:
    background: "#2e4053"
    foreground: "#f4f6f6"
    right:
      - text: "Project Summary"
        href: index.qmd
      - text: "Project Update"
        href: update.qmd
      - text: "Identification Key"
        href: id_key.qmd
      - text: "Questionnaire"
        href: questionnaire.qmd
      - text: "Handouts"
        href: handout.qmd

  page-footer:
    left: |
      <a href="https://www.maryam-nouriaiin.com/"><i class="bi bi-link"></i> Website</a><br>
      <a href="https://github.com/Maryam-NouriAiin/website_template" target="_blank">Template by Maryam Nouri-Aiin</a>
